
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk

from tcp import TCP
from data_models import IPData,PlayerData

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class ConnectionFrame:
        
    def __init__(self, connect,master=None, app=None):
        
        self.master = master
        self.frame =  tk.Frame(self.master)
        self.frame.pack()
        self.app = app    
        
        self.connect = connect
        self.ip = tk.StringVar()
        self.port = tk.IntVar()
        
        self.canvas = Canvas(
        self.frame,
        bg = "#FFFFFF",
        height = 982,
        width = 1512,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = self.canvas.create_image(
            719.0,
            443.0,
            image=entry_image_1
        )
        
        entry_1 = Entry(
            # self.frame,
            bd=0,
            bg="#FFFFFF",
            textvariable=self.ip,
            highlightthickness=0
            
        )
        entry_1.place(
            x=635.0,
            y=424.0,
            width=168.0,
            height=36.0
        )

        entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        
        entry_bg_2 = self.canvas.create_image(
            # self.frame,
            851.5,
            443.0,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#FFFFFF",
            textvariable=self.port,
            highlightthickness=0
        )
        entry_2.place(
            x=826.0,
            y=424.0,
            width=51.0,
            height=36.0
        )

        button_image_1 = PhotoImage(
            # self.frame,
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            # self.frame,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.try_connect,
            relief="flat",
            
        )
        button_1.place(
            x=709.0,
            y=475.0,
            width=95.0,
            height=32.0
        )

        self.canvas.create_text(
            501.0,
            273.0,
            anchor="nw",
            text="WELCOME TO BAAP RADIO",
            fill="#000000",
            font=("OpenSans SemiBold", 40 * -1)
        )

        Button(
            self.frame,
            text="Connect",
            command=self.try_connect
        ).pack()
        
    def try_connect(self):
        self.connect(self.ip.get(),self.port.get())
    
    def start_page(self):
        
        self.frame.pack()

    def go_back(self):
        self.frame.pack_forget()
        self.app.main_page()

