
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk 

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


# window = Tk()

# window.geometry("1216x814")
# window.configure(bg = "#FFFFFF")

class MainFrame:
    
    def __init__(self, master=None, app=None):
        
        self.master = master
        self.app = app
        self.frame =  tk.Frame(self.master)
        self.canvas = Canvas(
            self.frame,
            bg = "#FFFFFF",
            height = 814,
            width = 1216,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = self.canvas.create_image(
            608.0,
            179.0,
            image=image_image_1,
            
        )


        
        
        
        
    def start_page(self,data):
        # self.app.pack_forget()
        self.canvas.create_text(
            454.0,
            145.0,
            anchor="nw",
            text=data.site_name,
            fill="#FFFFFF",
            font=("JotiOne Regular", 64 * -1)
        )

        self.create_stations(data.radio_stn_list)
        
        self.frame.pack()

    def create_stations(self,data):
        # print(data)
        image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = self.canvas.create_image(
            161.0,
            441.0,
            image=image_image_2
        )

        

        self.canvas.create_text(
            48.0,
            355.0,
            anchor="nw",
            text=data[0].radio_stn_name,
            fill="#DF3030",
            font=("JotiOne Regular", 50 * -1)
        )

        self.canvas.create_text(
            48.0,
            410.0,
            anchor="nw",
            text=data[0].multicast_address,
            fill="#000000",
            font=("Itim Regular", 20 * -1)
        )

        self.canvas.create_rectangle(
            173.0,
            401.0,
            235.0,
            429.0,
            fill="#FFFFFF",
            outline="")

        self.canvas.create_text(
            184.0,
            404.0,
            anchor="nw",
            text=str(data[0].data_port),
            fill="#000000",
            font=("Itim Regular", 20 * -1)
        )

        self.canvas.create_rectangle(
            173.0,
            371.0,
            235.0,
            398.0,
            fill="#FFFFFF",
            outline="")

        self.canvas.create_text(
            178.0,
            374.0,
            anchor="nw",
            text=str(data[0].info_port),
            fill="#000000",
            font=("Itim Regular", 20 * -1)
        )

        image_image_3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        image_3 = self.canvas.create_image(
            155.0,
            488.0,
            image=image_image_3
        )
        
        print("done")
    def start_play(self,data):
        
        
        self.canvas.create_rectangle(
            30.0,
            547.0,
            1187.0,
            793.0,
            fill="#CF8227",
            outline="")

        self.canvas.create_rectangle(
            873.0,
            554.0,
            1175.0,
            786.0,
            fill="#FFFFFF",
            outline="")

        self.canvas.create_text(
            909.0,
            614.0,
            anchor="nw",
            text="Attention",
            fill="#000000",
            font=("JotiOne Regular", 50 * -1)
        )

        self.canvas.create_text(
            910.0,
            577.0,
            anchor="nw",
            text="Upcoming",
            fill="#000000",
            font=("Itim Regular", 35 * -1)
        )

        self.canvas.create_text(
            289.0,
            577.0,
            anchor="nw",
            text="Now Playing ",
            fill="#FFFFFF",
            font=("Itim Regular", 35 * -1)
        )

        self.canvas.create_text(
            293.0,
            681.0,
            anchor="nw",
            text="Time Left :",
            fill="#FFFFFF",
            font=("Itim Regular", 18 * -1)
        )

        self.canvas.create_text(
            378.0,
            680.0,
            anchor="nw",
            text="3456 sec",
            fill="#FFFFFF",
            font=("Itim Regular", 20 * -1)
        )

        self.canvas.create_text(
            289.0,
            616.0,
            anchor="nw",
            text="Binding Lights ",
            fill="#FFFFFF",
            font=("JotiOne Regular", 50 * -1)
        )

        image_image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = self.canvas.create_image(
            161.0,
            672.0,
            image=image_image_4
        )
        

        image_image_5 = PhotoImage(
            file=relative_to_assets("image_5.png"))
        image_5 = self.canvas.create_image(
            958.0,
            728.0,
            image=image_image_5
        )

    def go_back(self):
        self.frame.pack_forget()
        self.app.start_page()
        
# window.resizable(False, False)
# window.mainloop()


